routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('/pacientes')->name('paciente.')->namespace('paciente')->group(function(){
    //All the admin routes will be defined here...
    Route::get('/paciente/dashboard','pacientes\HomeController@index')->name('paciente.home');
    Route::get('/dashboard','HomeController@index')->name('home');
    Route::namespace('Auth')->group(function(){

        //Login Routes
        Route::get('/login','LoginController@showLoginForm')->name('login');
        Route::post('/login','LoginController@login');
        Route::post('/logout','LoginController@logout')->name('logout');

        //Forgot Password Routes
        Route::get('/password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('/password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');

        //Reset Password Routes
    });
  });
  Route::name('VerMiExpediente')->get('verExpe/{id}', 'PacientesController@verExpe');
  Route::name('showMiExpediente')->get('showExpe/{id}', 'PacientesController@showExpe');


Route::resource('usuarios', 'UsuariosController')->middleware('auth','RolAdmin:1');
Route::get('paciente/ayuda/{id}', 'PacientesController@ayuda')->middleware('auth','RolAdmin:2');
Route::get('paciente/paccomp', 'PacientesController@paccomp')->middleware('auth','RolAdmin:2');
Route::resource('paciente', 'PacientesController');
Route::resource('notas', 'NotasController')->middleware('auth','RolAdmin:3');


Route::name('CrearExpe')->get('historia_clinica/CrearExpe/{id}','HistoriaClinicaController@CrearExpe')->middleware('auth','RolAdmin:2');
Route::name('VerExpe')->get('historia_clinica/VerExpe/{id}','HistoriaClinicaController@VerExpe')->middleware('auth','RolAdmin:2');
Route::name('imprimir')->get('/imprimir/{id}', 'HistoriaClinicaController@imprimir')->middleware('auth','RolAdmin:2');
Route::resource('historia_clinica', 'HistoriaClinicaController')->middleware('auth','RolAdmin:2');


Route::name('CrearNE')->get('NoEvu/CrearNE/{id}','Nota_EvolucionController@Crear_NE')->middleware('auth','RolAdmin:2');
Route::name('print')->get('print/NE/{id}','Nota_EvolucionController@imprimir')->middleware('auth','RolAdmin:2');
Route::resource('NoEvu', 'Nota_EvolucionController')->middleware('auth','RolAdmin:2');
Route::resource('tiene', 'RolController' )->middleware( 'auth','RolAdmin:1');

app/Pacientes.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Pacientes extends Authenticatable
{
    //
    protected $table = "pacientes";
    protected $primaryKey = 'id';
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    protected $fillable = [
        'Nombre', 'Apellido_Paterno', 'Apellido_Materno','email', 'password', 'compartido','user_id','Sexo', 'isPaciente'
    ];
    protected $hidden = [
        'password', 'remember_token',
    ];
    public function historiaclinica()
    {
        return $this->hasMany('App\Historia_Clinica');
    }

    public function NoEv()
    {
        return $this->hasMany('App\Nota_Evolucion');
    }
    //Lit solo uso estos xd
    public function D1()
    {
        return $this->belongsToMany('App\User', 'historia_clinica','pacientes_id','user_id' )
        ->withPivot('id','Nombre','Edad','Direccion','Ante_AbuelosP',
        "Ante_AbuelosP" ,
        "Ante_AbuelosM" ,
        "Ante_Tios" ,
        "Ante_Papa" ,
        "Ante_Mama" ,
        "Ante_Hermanos" ,
        "Fecha_Nacimiento" ,
        "Lugar_Nacimiento" ,
        "Residencia_actual" ,
        "Escolaridad" ,
        "Estado_Civil" ,
        "Habitos_Higiene" ,
        "Habitos_Dieta" ,
        "Toxicomanias" ,
        "Enferme_infancia" ,
        "Cirugias" ,
        "Alergias" ,
        "Medica_Actual" ,
        "Menarca" ,
        "Ritmo_Menstrual" ,
        "FUM" ,
        "Gestas" ,
        "Paras" ,
        "Abortos" ,
        "Cesareas" ,
        "FUP" ,
        "USA" ,
        "Anticonseptivos" ,
        "Peso" ,
        "Talla" ,
        "Cabeza" ,
        "Ojos" ,
        "Oidos" ,
        "Nariz" ,
        "Boca" ,
        "Cuello" ,
        "Torax" ,
        "Forma" ,
        "Mov_Respira" ,
        "FR" ,
        "Ruido_Anormal" ,
        "FC" ,
        "Abdomen" ,
        "Extre_superior" ,
        "Extre_inferior" ,
        "created_at" ,
        "updated_at" );
    }

    public function NE1()
    {
        return $this->belongsToMany('App\User', 'nota_evolucion','paciente_id','doctor_id' )
        ->withPivot('id','paciente_id','doctor_id','Sintomas','Diagnostico','Tratamiento','Signos',"created_at" ,"updated_at" )
        ->orderBy('nota_evolucion.created_at', 'desc');
    }


}

app/Http/Controllers/PacientesController.php
<?php

namespace App\Http\Controllers;

use App\Historia_Clinica;
use App\Pacientes;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class PacientesController extends Controller
{
    //admin y doctor
    public function __construct()
    {
        $this->middleware('RolAdmin:4');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $users=User::find(Auth::id());
        $users->pacientes;
        return view('pacientes.index',compact('users'));
    }

    public function verExpe($id)
    {
        //
        $paciente=Pacientes::find($id);
        $paciente->D1;

        $pac_NE=Pacientes::find($id);
        $pac_NE->NE1;

        return view('pacientes.expediente',compact('paciente'),compact('pac_NE'));
    }

    public function showExpe($id)
    {
        //
        $paciente=Historia_Clinica::find($id);
        return view('pacientes.show',compact('paciente'));
    }



    public function paccomp(Request $request)
    {
        //
        $pacientes = Pacientes::all();
        return view('pacientes.show_other_pac',compact('pacientes'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('pacientes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Conocer la confirmacino
        if ($request['compartido'] == "on") {
           $compartido = 1;
        }
        else{
            $compartido = 0;
        }
        $users = Pacientes::create([
            'Nombre' => $request['Nombre'],
            'Apellido_Paterno' => $request['Apellido_Paterno'],
            'Apellido_Materno' => $request['Apellido_Materno'],
            'email' => $request['email'],
            'password' => Hash::make($request['password']),
            'compartido' => $compartido,
            'user_id' => $request['user_id'],
            'Sexo' => $request['Sexo'],
            'isPaciente' => '1',
        ]);

        return redirect()->route('paciente.index')
                        ->with('status','Paciente creado exitosamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Pacientes  $pacientes
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $paciente = Pacientes::find($id);
        return view('pacientes.view',compact('paciente'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //http://localhost/consultorio/public/paciente/897/edit
        $users = Pacientes::findOrfail($id);
        return view('pacientes.edit',compact('users'));
    }

    public function ayuda($id)
    {
        $paciente=Pacientes::find($id);
        return view('pacientes.confirmacion',compact('paciente'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Pacientes  $pacientes
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $compartido = $request['compartido'];
        if ($compartido == "on") {
            $compartido = 1;
         }
         else{
             $compartido = 0;
         }

        $users = Pacientes::findorfail($id);
        $users->Nombre =  $request->Nombre;
        $users->email = $request->email;
        $users->compartido = $compartido;
        $users->Sexo = $request->Sexo;
        $users->save();

        return redirect()->route('paciente.index')
                        ->with('success','Usuario actualizado exitosamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Pacientes  $pacientes
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Pacientes::find($id)->delete();
        return redirect()->route('paciente.index')
                        ->with('success','Product deleted successfully');
    }
}

app/Http/Controllers/paciente/HomeController.php
<?php

namespace App\Http\Controllers\paciente;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    //

    public function index(){
        return view('paciente.home');
    }
}

resources/views/pacientes/confirmacion.blade.php
@extends('layouts.app')
@extends('pacientes.index')
@section('modal')
<br>
    <div class="container" style="">
        <br>
        <center><div class="card" style="width: 18rem; background-color: darkred">
            <div class="card-body">
                <h3 style="color: white">¿Seguro que quiere eliminar a este paciente: {{$paciente->Nombre}} {{$paciente->Apellido_Paterno}} {{$paciente->Apellido_Materno}} ?</h3>
                <form action="{{ route('paciente.destroy',$paciente->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <a class="btn btn-primary" href="{{ route('paciente.index') }}"> Cancelar</a>
                    <button type="submit" class="btn btn-success">Confirmar</button>
                </form>
            </div>
        </div>
        <br>
    </div>
@endsection

resources/views/pacientes/create.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Agregar nuevo Paciente</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('paciente.index') }}"> Atras</a>
        </div>
    </div>
</div>

<form action="{{ route('paciente.store') }}" method="POST">
    @csrf
        <div class="form-group">
            <div class="justify-content-between align-items-center row">
                <div class="col-md-12 mx-auto">
                    <label for="Nombre"><strong>{{'Nombre(s) '}}</strong></label>
                    <input type="text" name="Nombre" id="Nombre" placeholder="Nombre" class="form-control input-sm" pattern="[a-z0-9A-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð #,.'-]{3,23}"
                    value="{{ old('Nombre') }}" required>
                </div>
            </div>
            <br>
            <div class="justify-content-between align-items-center row">
                <div class="col-md-4 mx-auto">
                    <label for="Apellido_Paterno"><strong>{{'Apellido Paterno '}}</strong></label>
                    <input type="text" name="Apellido_Paterno" id="Apellido_Paterno" placeholder="Apellido Paterno" class="form-control input-sm" pattern="[a-z0-9A-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð #,.'-]{3,23}"
                    value="{{ old('Apellido_Paterno') }}" required>
                </div>
                <div class="col-md-4 mx-auto">
                    <label for="Apellido_Materno"><strong>{{'Apellido Materno '}} </strong></label>
                    <input type="text" name="Apellido_Materno" id="Apellido_Materno" placeholder="Apellido Materno" class="form-control input-sm" pattern="[a-z0-9A-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð #,.'-]{3,23}"
                    value="{{ old('Apellido_Materno') }}">
                </div>
                <div class="col-md-4 mx-auto">
                    <label for="Sexo"><strong>{{'Sexo'}}</strong></label>
                    <select id="Sexo"  class="form-control" name="Sexo" autofocus>
                        <option value="M">Masculino</option>
                        <option value="F">Femenino</option>
                    </select>
                </div>
            </div>
            <br>
            <div class="form-group">
                <div class="form-group">
                    <strong>Correo:</strong>
                    <input type="text" name="email" class="form-control" placeholder="Correo" required>
                </div>
            </div>
            <div class="form-group">
                <div class="form-group">
                    <strong>Contraseña:</strong>
                    <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">
                </div>
            </div>
            <div class="form-group">
                <div class="form-group">
                    <strong>Confirmar Contraseña:</strong>
                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                </div>
            </div>
            <div class="form-group">
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="compartido" name="compartido">
                    <label class="custom-control-label" for="compartido"><strong>Compartir Paciente</strong></label>
                </div>
            </div>
            <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </div>

</form>
@endsection

resources/views/pacientes/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Editar Paciente {{$users->name}}</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('paciente.index') }}"> Atras</a>
        </div>
    </div>
</div>

<form action="{{ route('paciente.update', $users->id ) }}" method="POST">
    @csrf
    @method('PUT')
    <div class="form-group">
        <div class="justify-content-between align-items-center row">
            <div class="col-md-12 mx-auto">
                <label for="Nombre"><strong>{{'Nombre(s) '}}</strong></label>
                <input type="text" name="Nombre" id="Nombre" placeholder="Nombre" class="form-control input-sm" pattern="[a-z0-9A-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð #,.'-]{3,23}"
                value="{{ $users->Nombre }}" required>
            </div>
        </div>
        <br>
        <div class="justify-content-between align-items-center row">
            <div class="col-md-4 mx-auto">
                <label for="Apellido_Paterno"><strong>{{'Apellido Paterno '}}</strong></label>
                <input type="text" name="Apellido_Paterno" id="Apellido_Paterno" placeholder="Apellido Paterno" class="form-control input-sm" pattern="[a-z0-9A-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð #,.'-]{3,23}"
                value="{{ $users->Apellido_Paterno }}" required>
            </div>
            <div class="col-md-4 mx-auto">
                <label for="Apellido_Materno"><strong>{{'Apellido Materno '}} </strong></label>
                <input type="text" name="Apellido_Materno" id="Apellido_Materno" placeholder="Apellido Materno" class="form-control input-sm" pattern="[a-z0-9A-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð #,.'-]{3,23}"
                value="{{ $users->Apellido_Materno }}">
            </div>
            <div class="col-md-4 mx-auto">
                @if ($users->Sexo == "M")
                <label for="Sexo"><strong>{{'Sexo'}}</strong></label>
                <select id="Sexo"  class="form-control" name="Sexo" autofocus>
                    <option value="M">Masculino</option>
                    <option value="F">Femenino</option>
                </select>
                @else
                <label for="Sexo"><strong>{{'Sexo'}}</strong></label>
                <select id="Sexo"  class="form-control" name="Sexo" autofocus>
                    <option value="F">Femenino</option>
                    <option value="M">Masculino</option>
                </select>
                @endif
            </div>
        </div>
        <br>
        <div class="form-group">
            <div class="form-group">
                <strong>Correo:</strong>
                <input type="text" name="email" class="form-control" placeholder="Correo" value="{{ $users->email }}" required>
            </div>
        </div>
        <div class="form-group">
            @if ($users->compartido == 1)
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="compartido" name="compartido" checked >
                <label class="custom-control-label" for="compartido">Compartir Paciente</label>
            </div>
            @else
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="compartido" name="compartido">
                <label class="custom-control-label" for="compartido">Compartir Paciente</label>
            </div>
            @endif
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</div>

</form>
@endsection

resources/views/pacientes/index.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Mis Pacientes</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('paciente.create') }}"> Agregar Nuevo Paciente</a>
        </div>
        <br>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ url('paciente/paccomp') }}"> Todos los Pacientes </a>
        </div>
    </div>
</div>
<br>
<div class="table-responsive">
  <input class="form-control mb-4" id="tableSearch2" type="text" placeholder="Type something to search list items">
    <table id="example" class="table table-striped hover table-dark" style="width:100%">
  <thead>
      <tr>
          <th><center>#</th>
          <th><center>Nombre</th>
          <th><center>Sexo</th>
          <th><center>Email</th>
          <th><center>Compartido</th>
          <th><center>Doctor</th>
          <th><center>Accion</th>
          <th><center>Expediente Medico</th>

      </tr>
  </thead>
  <tbody id="myDIV">
      <!-- {{ $i = 0}} -->
      @forelse ($users->pacientes as $item)
      <tr>
        <td><center>{{ ++$i }}</td>
        <td><center>{{ $item->Nombre }}</td>
        @if ($item->Sex == "F" )
        <td><center>Femenino</td>
        @else
        <td><center>Masculino</td>
        @endif
        <td><center>{{ $item->email }}</td>
        @if ($item->compartido == 1)
        <td><center>Si</td>
        @else
        <td><center>No</td>
        @endif
        <td><center>{{ $users->Nombre }}</td>
        <td><center><div class="d-inline-flex">
            <a class="btn btn-warning" style="color: black" data-toggle="modal" data-target="#viewData{{$item->id}}">Ver</a>&nbsp;
            <a class="btn btn-primary"style="color: black" href="{{ route('paciente.edit',$item->id) }}">Editar</a>&nbsp;
            <a class="btn btn-danger"style="color: black" data-toggle="modal" data-target="#staticBackdrop{{$item->id}}" >Eliminar</a>
            </div>
        </td>
        <td><center>
            <div class="d-inline-flex">
            <a class="btn btn-warning" href="{{ route('VerExpe',$item->id) }}" >Expediente</a>
            </div>
        </td>
        </tr>
      @empty
      @endforelse
  </tbody>
  </table>
</div>


  @forelse ($users->pacientes as $item)
  <div class="modal fade" id="staticBackdrop{{$item->id}}" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <form action="{{ route('paciente.destroy',$item->id) }}" method="POST">
            @csrf
            @method('DELETE')
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">¿Seguro que quiere eliminar a este paciente: {{$item->Nombre}} {{$item->Apellido_Paterno}} {{$item->Apellido_Materno}} ?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <img img class="card-img-top" src="{{ asset('images/Delete.jpg') }}"
            alt="Card image cap">

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancerlar</button>
          <button type="submit" class="btn btn-danger">Confirmar</button>
        </div>
        </form>
      </div>
    </div>
  </div>
  @empty
  @endforelse

  @forelse ($users->pacientes as $item)
  <div class="modal fade" id="viewData{{$item->id}}" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="viewDataLabel">Paciente: {{$item->nombre}} {{$item->a_paterno}} {{$item->a_materno}} </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <p><Strong><h3>Nombre Completo:</h3></Strong> {{$item->Nombre}} {{$item->Apellido_Paterno}} {{$item->Apellido_Materno}}</p>
            @if ($item->Sex == "F" )
            <p><Strong><h3>Sexo:</h3></Strong> Femenino </p>
            @else
            <p><Strong><h3>Sexo:</h3></Strong> Masculino </p>
            @endif
            <p><Strong><h3>Correo:</h3></Strong> {{$item->email}} </p>
            <p><Strong><h3>Doctor Principal :</h3></Strong> {{ $item->user->Nombre }}</p>
            <p><Strong><h3>Fecha y hora de creacion :</h3></Strong> {{ $item->created_at }}</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>
  @empty

  @endforelse


@endsection

resources/views/pacientes/show_other_pac.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Todos los Pacientes</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('paciente.index') }}"> Atras</a>
        </div>
    </div>
</div>
<br>

<div class="table-responsive">
    <table id="example" class="table table-striped hover table-dark" style="width:100%">
  <thead>
      <tr>
          <th><center>#</th>
          <th><center>Nombre</th>
          <th><center>Email</th>
          <th><center>User</th>
          <th><center>Expediente</th>


      </tr>
  </thead>
  <tbody>
      <!-- {{ $i = 0}} -->
      @forelse ($pacientes as $item)
      @if ($item->compartido ==1)
      <tr>
        <td><center>{{ ++$i }}</td>
        <td><center>{{ $item->Nombre }} {{ $item->Apellido_Paterno }} {{ $item->Apellido_Materno }}</td>
        <td><center>{{ $item->email }}</td>
        <td><center>{{ $item->user->Nombre }}</td>
        <td><center>
            <div class="d-inline-flex">
            <a class="btn btn-warning" href="{{ route('VerExpe',$item->id) }}" >Expediente</a>
            </div>
        </td>
    </tr>
      @endif
      @empty
      @endforelse
  </tbody>
  </table>
  </div>

@endsection

resources/views/pacientes/view.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('paciente.index') }}"> Atras</a>
        </div>
    </div>
</div>
<div class="container">
    <p><h3>Nombre Completo:</h3> {{$paciente->Nombre}} {{$paciente->Apellido_Paterno}} {{$paciente->Apellido_Materno}}</p>
    <p><h3>Correo:</h3> {{$paciente->email}} </p>
    <p><h3>Confirmado:</h3> {{$paciente->compartido}}</p>
    <p><h3>Usuario Relacionado :</h3> {{$paciente->user_id}}</p>
</div>
@endsection