routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('/pacientes')->name('paciente.')->namespace('paciente')->group(function(){
    //All the admin routes will be defined here...
    Route::get('/paciente/dashboard','pacientes\HomeController@index')->name('paciente.home');
    Route::get('/dashboard','HomeController@index')->name('home');
    Route::namespace('Auth')->group(function(){

        //Login Routes
        Route::get('/login','LoginController@showLoginForm')->name('login');
        Route::post('/login','LoginController@login');
        Route::post('/logout','LoginController@logout')->name('logout');

        //Forgot Password Routes
        Route::get('/password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('/password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');

        //Reset Password Routes
    });
  });
  Route::name('VerMiExpediente')->get('verExpe/{id}', 'PacientesController@verExpe');
  Route::name('showMiExpediente')->get('showExpe/{id}', 'PacientesController@showExpe');


Route::resource('usuarios', 'UsuariosController')->middleware('auth','RolAdmin:1');
Route::get('paciente/ayuda/{id}', 'PacientesController@ayuda')->middleware('auth','RolAdmin:2');
Route::get('paciente/paccomp', 'PacientesController@paccomp')->middleware('auth','RolAdmin:2');
Route::resource('paciente', 'PacientesController');
Route::resource('notas', 'NotasController')->middleware('auth','RolAdmin:3');


Route::name('CrearExpe')->get('historia_clinica/CrearExpe/{id}','HistoriaClinicaController@CrearExpe')->middleware('auth','RolAdmin:2');
Route::name('VerExpe')->get('historia_clinica/VerExpe/{id}','HistoriaClinicaController@VerExpe')->middleware('auth','RolAdmin:2');
Route::name('imprimir')->get('/imprimir/{id}', 'HistoriaClinicaController@imprimir')->middleware('auth','RolAdmin:2');
Route::resource('historia_clinica', 'HistoriaClinicaController')->middleware('auth','RolAdmin:2');


Route::name('CrearNE')->get('NoEvu/CrearNE/{id}','Nota_EvolucionController@Crear_NE')->middleware('auth','RolAdmin:2');
Route::name('print')->get('print/NE/{id}','Nota_EvolucionController@imprimir')->middleware('auth','RolAdmin:2');
Route::resource('NoEvu', 'Nota_EvolucionController')->middleware('auth','RolAdmin:2');
Route::resource('tiene', 'RolController' )->middleware( 'auth','RolAdmin:1');

app/Notas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notas extends Model
{
    //
}

app/Http/Controllers/NotasController.php
<?php

namespace App\Http\Controllers;

use App\Notas;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

use function GuzzleHttp\Promise\all;

class NotasController extends Controller
{
    //todos menos paciente
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('RolAdmin:3');
    }
    /**
     *
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $notas=Notas::join('users','notas.id_Emisor','users.id')
        ->select('notas.*','Nombre')->get();
        return view('Notas.index',compact('notas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   $notas=DB::table('users')->join('rol_permisos','users.id','rol_permisos.user_id')->where('rol_id','3')->select('id','Nombre')->get();
        return view('Notas.create',compact('notas'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         Notas::insert([
            'Id_Receptor' => $request['Id_Receptor'],
             'Id_Emisor' => $request['Id_Emisor'],
            'Asunto' => $request['Asunto'],
             'Descripcion' => $request['Descripcion'],
             'created_at' => today(),
         ]);
         return redirect()->route('notas.index')
        ->with('success','Nota creada exitosamente.');
         return view('Notas.create',compact('notas'));

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Notas  $notas
     * @return \Illuminate\Http\Response
     */
    public function show(Notas $notas)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Notas  $notas
     * @return \Illuminate\Http\Response
     */
    public function edit(Notas $notas)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Notas  $notas
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Notas $notas)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Notas  $notas
     * @return \Illuminate\Http\Response
     */
    public function destroy(Notas $notas)
    {
        //
    }
}

resources/views/Notas/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Registro') }}</div>

                <div class="card-body">
                    <form action="{{route('notas.store')}}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <label for="Asunto" class="col-md-4 col-form-label text-md-right">{{ __('Asunto') }}</label>

                            <div class="col-md-6">
                                <input id="Asunto" type="text" class="form-control @error('Asunto') is-invalid @enderror" name="Asunto" autofocus>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="Descripcion" class="col-md-4 col-form-label text-md-right">{{ __('Descripción') }}</label>
                            <div class="col-md-6 ">
                            <textarea name="Descripcion" id="Descripcion" cols="30" rows="10" type="text" class="form-control @error('Descripcion') is-invalid @enderror"></textarea>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="Id_Receptor" class="col-md-4 col-form-label text-md-right ">{{ __(' Secretaria') }}</label>

                            <div class="col-md-6">
                                <select id="Id_Receptor"  class="form-control" name="Id_Receptor" autofocus>
                                    @foreach ($notas as $secre)
                                      <option value={{$secre->id}}>{{$secre->Nombre}}</option> 
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <input type="hidden" name="Id_Emisor" value="{{ Auth::user()->id }}">                    
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                                <a class="btn btn-outline-danger" href="{{route('usuarios.index')}}">Regresar</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/Notas/index.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Mis Notas</h2>
        </div>
        {{--  <div class="pull-right">
            <a class="btn btn-success" href="{{ route('notas.create') }}"> Agregar Nuevo Paciente</a>
        </div>  --}}
        {{--  <br>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ url('paciente/paccomp') }}"> Todos los Pacientes </a>
        </div>
    </div>  --}}
</div>
<br>
<div class="table-responsive">
  <input class="form-control mb-4" id="tableSearch2" type="text" placeholder="Type something to search list items">
    <table id="example" class="table table-striped hover table-dark" style="width:100%">
  <thead>
      <tr>
          <th>#</th>
          <th>Asunto</th>
          <th>Doctor</th>
          <th>Accion</th>

      </tr>
  </thead>
  <tbody id="myDIV">
    @forelse ($notas as $item)
      <tr>
        <td>{{ $loop->iteration  }}</td>
        <td>{{$item->Asunto}}</td>
        <td >
          <option value={{$item->id_Emisor}}>
            {{'Dr.'}} {{$item->Nombre}}
          </option>
          </td>
        {{--  <td>{{ $item->email }}</td>
        <td>{{ $item->compartido }}</td>
        <td>{{ $users->Nombre }}</td>  --}}
      <td>
            <a class="btn btn-warning" data-toggle="modal" data-target="#viewData{{$item->id}}">Ver</a>
    </td>
    </tr>
      @empty

       @endforelse
  </tbody>
  </table>
  </div>

  @forelse ($notas as $item)
  <div class="modal fade" id="viewData{{$item->id}}" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="viewDataLabel">Asunto: {{$item->Asunto}} </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <p><Strong><h3>Descripción:</h3></Strong> {{$item->Descripcion}}</p>
            <p><Strong><h3>Fecha y hora de creacion :</h3></Strong> {{ $item->created_at }}</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>
  @empty

  @endforelse
  <!-- Modal -->


@endsection