routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('/pacientes')->name('paciente.')->namespace('paciente')->group(function(){
    //All the admin routes will be defined here...
    Route::get('/paciente/dashboard','pacientes\HomeController@index')->name('paciente.home');
    Route::get('/dashboard','HomeController@index')->name('home');
    Route::namespace('Auth')->group(function(){

        //Login Routes
        Route::get('/login','LoginController@showLoginForm')->name('login');
        Route::post('/login','LoginController@login');
        Route::post('/logout','LoginController@logout')->name('logout');

        //Forgot Password Routes
        Route::get('/password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('/password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');

        //Reset Password Routes
    });
  });
  Route::name('VerMiExpediente')->get('verExpe/{id}', 'PacientesController@verExpe');
  Route::name('showMiExpediente')->get('showExpe/{id}', 'PacientesController@showExpe');


Route::resource('usuarios', 'UsuariosController')->middleware('auth','RolAdmin:1');
Route::get('paciente/ayuda/{id}', 'PacientesController@ayuda')->middleware('auth','RolAdmin:2');
Route::get('paciente/paccomp', 'PacientesController@paccomp')->middleware('auth','RolAdmin:2');
Route::resource('paciente', 'PacientesController');
Route::resource('notas', 'NotasController')->middleware('auth','RolAdmin:3');


Route::name('CrearExpe')->get('historia_clinica/CrearExpe/{id}','HistoriaClinicaController@CrearExpe')->middleware('auth','RolAdmin:2');
Route::name('VerExpe')->get('historia_clinica/VerExpe/{id}','HistoriaClinicaController@VerExpe')->middleware('auth','RolAdmin:2');
Route::name('imprimir')->get('/imprimir/{id}', 'HistoriaClinicaController@imprimir')->middleware('auth','RolAdmin:2');
Route::resource('historia_clinica', 'HistoriaClinicaController')->middleware('auth','RolAdmin:2');


Route::name('CrearNE')->get('NoEvu/CrearNE/{id}','Nota_EvolucionController@Crear_NE')->middleware('auth','RolAdmin:2');
Route::name('print')->get('print/NE/{id}','Nota_EvolucionController@imprimir')->middleware('auth','RolAdmin:2');
Route::resource('NoEvu', 'Nota_EvolucionController')->middleware('auth','RolAdmin:2');
Route::resource('tiene', 'RolController' )->middleware( 'auth','RolAdmin:1');

resources/views/Notas_evolucion/create.blade.php
@extends('layouts.app')
@section('content')
<br>
<br>
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Agregar de Nota Evolucion</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('VerExpe',$paciente->id) }}"> Atras</a>
        </div>
    </div>
</div>

<form action="{{ route('NoEvu.store',$paciente->id) }}" method="POST">
    @csrf
    <div class="form-group">
        <br>
       <div class="form-group">
           <label for="Sintomas">{{'Sintomas'}}</label>
           <textarea type="text" name="Sintomas" id="Sintomas" class="form-control input-sm"
           value="{{old('Sintomas')}}"></textarea>
       </div>
       <div class="form-group">
        <label for="Signos">{{'Signos'}}</label>
        <textarea type="text" name="Signos" id="Signos" class="form-control input-sm"
        value="{{old('Signos')}}"></textarea>
    </div>
       <div class="justify-content-between align-items-center row">
           <div class="col-md-6 mx-auto">
               <label for="Diagnostico">{{'Diagnostico'}}</label>
               <textarea type="text" name="Diagnostico" id="Diagnostico" class="form-control @error('Edad') is-invalid @enderror input-sm"
               value="{{ old('Diagnostico') }}" required></textarea>
           </div>
           <div class="col-md-6 mx-auto">
               <label for="Tratamiento">{{'Tratamiento'}}</label>
               <textarea  type="text" name="Tratamiento" id="Tratamiento" class="form-control @error('Direccion') is-invalid @enderror input-sm"
               value="{{ old('Tratamiento') }}" required></textarea>
           </div>
       </div>
       <br>
       <input type="hidden" name="paciente_id" value="{{ $paciente->id }}">
        <input type="hidden" name="doctor_id" value="{{ Auth::user()->id }}">
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
@endsection

resources/views/Notas_evolucion/edit.blade.php
@extends('layouts.app')
@section('content')
<br>
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Editar Historia Clinica</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('VerExpe',$nota->paciente_id) }}"> Atras</a>
        </div>
    </div>
</div>
<form action="{{ route('NoEvu.update',$nota->id) }}" method="POST">
    @csrf
    @method('PUT')
    <div class="form-group">
        <br>
       <div class="form-group">
           <label for="Sintomas">{{'Sintomas'}}</label>
           <textarea type="text" name="Sintomas" id="Sintomas" class="form-control input-sm"
           >{{ $nota->Sintomas}}</textarea>
       </div>
       <div class="form-group">
        <label for="Signos">{{'Signos'}}</label>
        <textarea type="text" name="Signos" id="Signos" class="form-control input-sm"
        >{{ $nota->Signos}}</textarea>
        </div>
       <div class="justify-content-between align-items-center row">
           <div class="col-md-6 mx-auto">
               <label for="Diagnostico">{{'Diagnostico'}}</label>
               <textarea type="text" name="Diagnostico" id="Diagnostico" class="form-control @error('Edad') is-invalid @enderror input-sm"
               >{{ $nota->Diagnostico}}</textarea>
           </div>
           <div class="col-md-6 mx-auto">
               <label for="Tratamiento">{{'Tratamiento'}}</label>
               <textarea  type="text" name="Tratamiento" id="Tratamiento" class="form-control @error('Direccion') is-invalid @enderror input-sm"
               >{{ $nota->Tratamiento}}</textarea>
           </div>
       </div>
       <br>
       <input type="hidden" name="id" value="{{ $nota->id }}">
        <input type="hidden" name="id_pacc" value="{{ $nota->paciente_id }}">
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>
@endsection